version: "3.7"

services:
  webgl-preview:
    image: ${WEBGL_PREVIEW_IMAGE:-hkccr.ccs.tencentyun.com/plugins/webgl-preview:main}
    restart: always
    networks:
      - proxy
      - internal
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.entrypoints=websecure"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.rule=Host(`webgl-preview.plugins.xrugc.com`)"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.tls=true"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.entrypoints=websecure"
      - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.rule=Host(`webgl-preview.d.plugins.xrugc.com`)"
      - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.tls=true"
      - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.webgl-preview-plugins-xrugc-com.loadbalancer.server.port=80"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.entrypoints=websecure"
        - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.rule=Host(`webgl-preview.plugins.xrugc.com`)"
        - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.tls=true"
        - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.tls.certresolver=letsencrypt"
        - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.entrypoints=websecure"
        - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.rule=Host(`webgl-preview.d.plugins.xrugc.com`)"
        - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.tls=true"
        - "traefik.http.routers.webgl-preview-d-plugins-xrugc-com-secure.tls.certresolver=letsencrypt"
        - "traefik.http.services.webgl-preview-plugins-xrugc-com.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  internal:
