version: "3.7"

services:
  webgl-preview:
    image: hkccr.ccs.tencentyun.com/plugins/webgl-preview:develop
    restart: always
    networks:
      - proxy
      - internal
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.entrypoints=websecure"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.rule=Host(`webgl-preview.plugins.xrugc.com`)"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.middlewares=test-compress@file"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.tls=true"
      - "traefik.http.routers.webgl-preview-plugins-xrugc-com-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.webgl-preview-plugins-xrugc-com.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  internal:
